### ISSUE TITLE
Error Installing: tensorflow_cpu_aws

### ISSUE THREAD

**Issue by exius-netrunner** [willhughes11/facial-recognition-and-rating-api#2]
First, I want to note that I am on Windows 11.

When I attempt to install the dependencies, they all install as expected except for tensorflow_cpu_aws.
After I run it, it looks like it runs successfully on my localhost address but figured I'd just make a note of this on here.

Tensorflow itself also installs just fine, it's only this cpu_aws version in the requirements.txt that isn't and not sure what it handles or if I'll run into issues later.

The exact error message my console throws is this:

ERROR: Could not find a version that satisfies the requirement tensorflow_cpu_aws==2.10.0rc3 (from versions: none)
ERROR: No matching distribution found for tensorflow_cpu_aws==2.10.0rc3

**Comment by willhughes11** [comment]
Removed tensorflow_cpu_aws from requirements.txt
